version: 0.2 

env:
  variables:
    CX_SERVER: "https://cxapactrial.checkmarx.net/" 
    CX_TOKEN: "d27c4fab982c265ae34c2e0acbe95b1557844e7e65e80232b3b6bfb467dde148"
    CX_TEAM: "CxServer\\SP\\APAC"
    CX_PROJECT_NAME: "WebGoat-Legacy-AWS"
    CX_PRESET: "Checkmarx Default"
    CX_HIGH: 1
    CX_MEDIUM: 2
    CX_LOW: 3

phases: 
  install: 
    runtime-versions: 
      java: openjdk11 
  post_build: 
    commands: 
      - wget -O ~/cxcli.zip https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-2020.3.1.zip
      - unzip ~/cxcli.zip -d ~/cxcli 
      - rm -rf ~/cxcli.zip 
      - chmod +x ~/cxcli/runCxConsole.sh 
      - ~/cxcli/runCxConsole.sh Scan -verbose -CxServer $CX_SERVER -CxToken $CX_TOKEN -ProjectName "$CX_TEAM\\$CX_PROJECT_NAME" -preset "$CX_PRESET" -LocationType folder -LocationPath "$CODEBUILD_SRC_DIR" -SASTHigh $CX_HIGH -SASTMedium $CX_MEDIUM -SASTLow $CX_LOW -enableSca -scaAccount $SCA_ACCOUNT-scaUsername $SCA_USERNAME -scaPassword $SCA_PASSWORD scahigh $SCA_HIGH -scamedium $SCA_MEDIUM -scalow $SCA_LOW